ASFLAGS_ADDITIONAL = -c -g -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10801 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/arduinotarget/registry/..
STACK_SIZE = 64
